# Generated by Django 4.2 on 2023-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nation', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('squad', models.CharField(max_length=30)),
                ('comp', models.CharField(max_length=30)),
                ('matchesplayed', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('goals', models.FloatField()),
                ('shots', models.FloatField()),
                ('sot', models.FloatField()),
                ('sotperc', models.FloatField()),
                ('goalspersh', models.FloatField()),
                ('goalspersot', models.FloatField()),
            ],
        ),
    ]
