# Generated by Django 4.2.1 on 2023-05-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_players_aerlost_players_aerwon_players_aerwonperc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('favoritedPlayers', models.ManyToManyField(to='api.players')),
            ],
        ),
    ]
