# Generated by Django 4.2.1 on 2023-05-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_usercreds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCreds',
            new_name='UserCred',
        ),
    ]
