# Generated by Django 4.2.1 on 2023-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_usercreds_usercred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercred',
            name='favoritedPlayers',
        ),
        migrations.AddField(
            model_name='usercred',
            name='favoritedPlayers',
            field=models.CharField(default='', max_length=255, verbose_name='Favorited Players'),
        ),
    ]
