# Generated by Django 4.2.1 on 2023-05-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usercred_favoritedplayers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='usercred',
            name='password',
        ),
    ]
