# Generated by Django 4.2.1 on 2023-05-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_user_remove_usercred_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('topscorer', models.CharField(max_length=100)),
                ('topteam', models.CharField(max_length=100)),
                ('lastgame1', models.CharField(max_length=100)),
                ('lastgame2', models.CharField(max_length=100)),
                ('lastgame3', models.CharField(max_length=100)),
                ('nextgame1', models.CharField(max_length=100)),
                ('nextgame2', models.CharField(max_length=100)),
                ('nextgame3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('matchesplayed', models.IntegerField(null=True)),
                ('wins', models.IntegerField(null=True)),
                ('draws', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('goalsmade', models.IntegerField(null=True)),
                ('goalsgave', models.IntegerField(null=True)),
                ('goaldiff', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('pointspermatch', models.FloatField(null=True)),
                ('expectedgoals', models.FloatField(null=True)),
                ('expectedgoalsallowed', models.FloatField(null=True)),
                ('expectedgoaldiff', models.FloatField(null=True)),
                ('Attendance', models.IntegerField(null=True)),
                ('TopTeamScorer', models.CharField(max_length=50)),
                ('Goalkeeper', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usercred',
            name='favoriteLeagues',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usercred',
            name='favoriteTeams',
            field=models.CharField(default='', max_length=255),
        ),
    ]
