from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class Players(models.Model):
    name = models.CharField(_("Player"),max_length=30)
    nation = models.CharField(_("Nation"),max_length = 30)
    position = models.CharField(_("Pos"),max_length=30)
    squad = models.CharField(_("Squad"),max_length=30)
    comp = models.CharField(_("Comp"),max_length=30)
    age = models.IntegerField(_("Age"), null = True)
    matchesplayed = models.IntegerField(_("MP"), null = True)
    starts = models.IntegerField(_("Starts"), null = True)
    minutes = models.IntegerField(_("Min"), null = True)
    goals = models.FloatField(_("Goals"), null = True)
    shots = models.FloatField(_("Shots"), null = True)
    sot = models.FloatField(_("SoT"), null = True)
    sotperc = models.FloatField(_("Sot%"), null = True)
    goalspersh = models.FloatField(_("G/Sh"), null = True)
    goalspersot = models.FloatField(_("G/SoT"), null = True)
    ShoDist = models.FloatField(_("ShoDist"), null = True)
    ShoFK = models.FloatField(_("ShoFK"), null = True)
    ShoPK = models.FloatField(_("ShoPK"), null = True)
    PKatt = models.FloatField(_("PKatt"), null = True)
    PasTotCmp = models.FloatField(_("PasTotCmp"), null = True)
    PasTotAtt = models.FloatField(_("PasTotAtt"), null = True)
    PasTotCmpperc = models.FloatField(_("PasTotCmp%"), null = True)
    PasTotDist = models.FloatField(_("PasTotDist"), null = True)
    PasTotPrgDist = models.FloatField(_("PasTotPrgDist"), null = True)
    PasShoCmp = models.FloatField(_("PasShoCmp"), null = True)
    PasShoAtt = models.FloatField(_("PasShoAtt"), null = True)
    PasShoCmpperc = models.FloatField(_("PasShoCmp%"), null = True)
    PasMedCmp = models.FloatField(_("PasMedCmp"), null = True)
    PasMedAtt = models.FloatField(_("PasMedAtt"), null = True)
    PasMedCmpperc = models.FloatField(_("PasMedCmp%"), null = True)
    PasLonCmp = models.FloatField(_("PasLonCmp"), null = True)
    PasLonAtt = models.FloatField(_("PasLonAtt"), null = True)
    PasLonCmpperc = models.FloatField(_("PasLonCmp%"), null = True)
    Assists = models.FloatField(_("Assists"), null = True)
    PasAss = models.FloatField(_("PasAss"), null = True)
    Pas3rd = models.FloatField(_("Pas3rd"), null = True)
    PPA = models.FloatField(_("PPA"), null = True)
    CrsPA = models.FloatField(_("CrsPA"), null = True)
    PasProg = models.FloatField(_("PasProg"), null = True)
    PasAtt = models.FloatField(_("PasAtt"), null = True)
    PasLive = models.FloatField(_("PasLive"), null = True)
    PasDead = models.FloatField(_("PasDead"), null = True)
    PasFK = models.FloatField(_("PasFK"), null = True)
    TB = models.FloatField(_("TB"), null = True)
    PasPress = models.FloatField(_("PasPress"), null = True)
    Sw = models.FloatField(_("Sw"), null = True)
    PasCrs = models.FloatField(_("PasCrs"), null = True)
    CK = models.FloatField(_("CK"), null = True)
    CkIn = models.FloatField(_("CkIn"), null = True)
    CkOut = models.FloatField(_("CkOut"), null = True)
    CkStr = models.FloatField(_("CkStr"), null = True)
    PasGround = models.FloatField(_("PasGround"), null = True)
    PasLow = models.FloatField(_("PasLow"), null = True)
    PasHigh = models.FloatField(_("PasHigh"), null = True)
    PaswLeft = models.FloatField(_("PaswLeft"), null = True)
    PaswRight = models.FloatField(_("PaswRight"), null = True)
    PaswHead = models.FloatField(_("PaswHead"), null = True)
    TI = models.FloatField(_("TI"), null = True)
    PaswOther = models.FloatField(_("PaswOther"), null = True)
    PasCmp = models.FloatField(_("PasCmp"), null = True)
    PasOff = models.FloatField(_("PasOff"), null = True)
    PasOut = models.FloatField(_("PasOut"), null = True)
    PasInt = models.FloatField(_("PasInt"), null = True)
    PasBlocks = models.FloatField(_("PasBlocks"), null = True)
    SCA = models.FloatField(_("SCA"), null = True)
    ScaPassLive = models.FloatField(_("ScaPassLive"), null = True)
    ScaPassDead = models.FloatField(_("ScaPassDead"), null = True)
    ScaDrib = models.FloatField(_("ScaDrib"), null = True)
    ScaSh = models.FloatField(_("ScaSh"), null = True)
    ScaFld = models.FloatField(_("ScaFld"), null = True)
    ScaDef = models.FloatField(_("ScaDef"), null = True)
    GCA = models.FloatField(_("GCA"), null = True)
    GcaPassLive = models.FloatField(_("GcaPassLive"), null = True)
    GcaPassDead = models.FloatField(_("GcaPassDead"), null = True)
    GcaDrib = models.FloatField(_("GcaDrib"), null = True)
    GcaSh = models.FloatField(_("GcaSh"), null = True)
    GcaFld = models.FloatField(_("GcaFld"), null = True)
    GcaDef = models.FloatField(_("GcaDef"), null = True)
    Tkl = models.FloatField(_("Tkl"), null = True)
    TklWon = models.FloatField(_("TklWon"), null = True)
    TklDef3rd = models.FloatField(_("TklDef3rd"), null = True)
    TklMid3rd = models.FloatField(_("TklMid3rd"), null = True)
    TklAtt3rd = models.FloatField(_("TklAtt3rd"), null = True)
    TklDri = models.FloatField(_("TklDri"), null = True)
    TklDriAtt = models.FloatField(_("TklDriAtt"), null = True)
    TklDriperc = models.FloatField(_("TklDri%"), null = True)
    TklDriPast = models.FloatField(_("TklDriPast"), null = True)
    Press = models.FloatField(_("Press"), null = True)
    PresSucc = models.FloatField(_("PresSucc"), null = True)
    Pressperc = models.FloatField(_("Press%"), null = True)
    PresDef3rd = models.FloatField(_("PresDef3rd"), null = True)
    PresMid3rd = models.FloatField(_("PresMid3rd"), null = True)
    PresAtt3rd = models.FloatField(_("PresAtt3rd"), null = True)
    Blocks = models.FloatField(_("Blocks"), null = True)
    BlkSh = models.FloatField(_("BlkSh"), null = True)
    BlkShSv = models.FloatField(_("BlkShSv"), null = True)
    BlkPass = models.FloatField(_("BlkPass"), null = True)
    Int = models.FloatField(_("Int"), null = True)
    TklplusInt = models.FloatField(_("Tkl+Int"), null = True)
    Clr = models.FloatField(_("Clr"), null = True)
    Err = models.FloatField(_("Err"), null = True)
    Touches = models.FloatField(_("Touches"), null = True)
    TouDefPen = models.FloatField(_("TouDefPen"), null = True)
    TouDef3rd = models.FloatField(_("TouDef3rd"), null = True)
    TouMid3rd = models.FloatField(_("TouMid3rd"), null = True)
    TouAtt3rd = models.FloatField(_("TouAtt3rd"), null = True)
    TouAttPen = models.FloatField(_("TouAttPen"), null = True)
    TouLive = models.FloatField(_("TouLive"), null = True)
    DriSucc = models.FloatField(_("DriSucc"), null = True)
    DriAtt = models.FloatField(_("DriAtt"), null = True)
    DriSuccperc = models.FloatField(_("DriSucc%"), null = True)
    DriPast = models.FloatField(_("DriPast"), null = True)
    DriMegs = models.FloatField(_("DriMegs"), null = True)
    Carries = models.FloatField(_("Carries"), null = True)
    CarTotDist = models.FloatField(_("CarTotDist"), null = True)
    CarPrgDist = models.FloatField(_("CarPrgDist"), null = True)
    CarProg = models.FloatField(_("CarProg"), null = True)
    Car3rd = models.FloatField(_("Car3rd"), null = True)
    CPA = models.FloatField(_("CPA"), null = True)
    CarMis = models.FloatField(_("CarMis"), null = True)
    CarDis = models.FloatField(_("CarDis"), null = True)
    RecTarg = models.FloatField(_("RecTarg"), null = True)
    Rec = models.FloatField(_("Rec"), null = True)
    Recperc = models.FloatField(_("Rec%"), null = True)
    RecProg = models.FloatField(_("RecProg"), null = True)
    CrdY = models.FloatField(_("CrdY"), null = True)
    CrdR = models.FloatField(_("CrdR"), null = True)
    twoCrdY = models.FloatField(_("2CrdY"), null = True)
    Fls = models.FloatField(_("Fls"), null = True)
    Fld = models.FloatField(_("Fld"), null = True)
    Off = models.FloatField(_("Off"), null = True)
    Crs = models.FloatField(_("Crs"), null = True)
    TklW = models.FloatField(_("TklW"), null = True)
    PKwon = models.FloatField(_("PKwon"), null = True)
    PKcon = models.FloatField(_("PKcon"), null = True)
    OG = models.FloatField(_("OG"), null = True)
    Recov = models.FloatField(_("Recov"), null = True)
    AerWon = models.FloatField(_("AerWon"), null = True)
    AerLost = models.FloatField(_("AerLost"), null = True)
    AerWonperc = models.FloatField(_("AerWon%"), null = True)

    
    
  






